// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
       return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        return web;
        
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1n2pKfH_lx5NBxMaRW5vLIiwWdfluyT0',
    appId: '1:10015435752:web:227dafd9758e400600125d',
    messagingSenderId: '10015435752',
    projectId: 'flutter-test-f96b9',
    authDomain: 'flutter-test-f96b9.firebaseapp.com',
    databaseURL: 'https://flutter-test-f96b9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-f96b9.appspot.com',
    measurementId: 'G-R4VP85839J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Ob2cQEkaC1JgEU83yNanF1hSWehdicI',
    appId: '1:10015435752:android:b2f372b989ecdefd00125d',
    messagingSenderId: '10015435752',
    projectId: 'flutter-test-f96b9',
    databaseURL: 'https://flutter-test-f96b9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-f96b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSKIfVs5Io2WHhwGMQs91l_DolLWOsCb8',
    appId: '1:10015435752:ios:f81739ff74c74ede00125d',
    messagingSenderId: '10015435752',
    projectId: 'flutter-test-f96b9',
    databaseURL: 'https://flutter-test-f96b9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-f96b9.appspot.com',
    iosClientId: '10015435752-q0kqpg60o0k3g5us25uqc7l42778vjdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSKIfVs5Io2WHhwGMQs91l_DolLWOsCb8',
    appId: '1:10015435752:ios:04a6daac8bd9a86d00125d',
    messagingSenderId: '10015435752',
    projectId: 'flutter-test-f96b9',
    databaseURL: 'https://flutter-test-f96b9-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-f96b9.appspot.com',
    iosClientId: '10015435752-tv3leoked1ejltrc00o4dadetpdmvskb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrudApp.RunnerTests',
  );
}
